# Generated by Django 4.1.1 on 2022-09-24 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insumo', '0003_alter_insumo_existencia'),
        ('entrada', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleentrada',
            name='entrada',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='entrada.entrada', verbose_name='Entrada'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detalleentrada',
            name='cantidad',
            field=models.PositiveIntegerField(help_text='solo incluir numeros', verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='detalleentrada',
            name='insumo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insumo.insumo', verbose_name='Nombre Insumo'),
        ),
    ]
