# Generated by Django 4.1.1 on 2022-09-24 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0002_alter_detallesolicitud_insumo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallesolicitud',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Subtotal'),
        ),
    ]
