# Generated by Django 4.1.1 on 2022-09-24 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitud', '0003_alter_detallesolicitud_subtotal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallesolicitud',
            name='subtotal',
        ),
    ]
