# Generated by Django 4.1.1 on 2022-09-24 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='existencia',
            field=models.IntegerField(default=0, verbose_name='Existencia'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio'),
        ),
    ]
