# Generated by Django 4.1.1 on 2022-09-24 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumo', '0002_insumo_existencia_alter_insumo_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='existencia',
            field=models.IntegerField(default=0, editable=False, verbose_name='Existencia'),
        ),
    ]
