# Generated by Django 4.1.1 on 2022-09-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre de Servicio')),
                ('descripcion', models.CharField(max_length=50, verbose_name='apellidos')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'db_table': 'servicio',
            },
        ),
    ]
